DeviceInfo:
  IpAddress: "192.168.3.3"
  CameraTimeout: 2000
  Height: 1
  VirtualFrameHeight: 1024
  Delay: 0.5
WriteSetup:
  AnalogControls:
    GainAuto:
      - "Off"
      - "Once"
      - "Continuous"
    GainSelector:
      - "DigitalAll"
      - "AnalogAll"
    GainRaw:
      value: 2000
      min: 256
      max: 2047
      step: 1
    BlackLevelSelector:
      - "All"
    BlackLevelRaw:
      value: 50
      min: -2048
      max: 2047
      step: 1
    GammaEnable:
      - "False"
      - "True"
    GammaSelector:
      - "User"
      - "sRGB"
    Gamma:
      value: 0.1
      min: 0.1
      max: 0.4
      step: 0.1
  ImageFormatControls:
    PixelFormat:
      - "Mono8"
    TestImageSelector:
      - "Off"
  AOIControls:
    Width:
      value: 2048
      min: 1
      max: 2048
      step: 1
    Height:
      value: 1
      min: 1
      max: 12288
      step: 1
    CenterX:
      - "True"
      - "False"
    BinningHorizontal:
      value: 1
      min: 1
      max: 4
      step: 1
  AcquisitionControls:
    ExposureAuto:
      - "Off"
      - "Once"
      - "Continuous"
    ExposureTimeRaw:
      value: 17132
      min: 20
      max: 100000
      step: 1
    AcquisitionLineRateAbs:
      value: 30030.03
      min: 100
      max: 50000
      step: 0.05
ReadSetup:
  AcquisitionControls:
    - "GainAuto"
    - "GainSelector" 
    - "GainRaw" 
    - "BlackLevelSelector" 
    - "BlackLevelRaw" 
    - "GammaEnable" 
    - "GammaSelector" 
    - "Gamma" 
    - "PixelFormat" 
    - "TestImageSelector" 
    - "Width" 
    - "Height" 
    - "CenterX" 
    - "BinningHorizontal" 
    - "ExposureAuto" 
    - "ExposureTimeRaw" 
    - "AcquisitionLineRateAbs"
    - "ResultingLineRateAbs"
    - "ResultingFrameRateAbs"